* org-board.el
** Motivation
   Org-board is a bookmarking and web archival system for Emacs Org
   mode, building on ideas from [[https://pinboard.in][Pinboard]].  Org-board archives your
   bookmarks so that you can access them even when you're not online,
   or when the site hosting them goes down.  Org-board uses `wget' as
   a backend for archival, so any of `wget''s options can be used
   directly from org-board.  This means you can download whole sites
   for archival with a couple of keystrokes, while keeping track of
   your archives from a simple Org file.
** Summary
   In org-board, a bookmark is represented by an Org heading of any
   level, with a URL property containing one or more URLs.  Once such
   a heading is created, a call to `org-board-archive' creates a
   unique ID and directory for the entry via `org-attach', archives
   the contents and requisites of the page(s) listed in the URL
   property using `wget', and saves them inside the entry's directory.
   A link to the (timestamped) root archive folder is created in the
   property ARCHIVED_AT.  Multiple archives can be made for each
   entry.  Additional options to pass to `wget' can be specified via
   the property `WGET_OPTIONS'.
** User commands
   `org-board-archive' :: archive the current entry, creating a
   unique ID and directory via org-attach if necessary.
   `org-board-new' :: prompt for a URL to add to the current entry's
   properties, then archive it immediately.
   `org-board-delete-all' :: delete all the archives for this entry by
   deleting the org-attach directory.
   `org-board-open' :: search for html files in the latest archive's
   directory, and show them in a dired buffer.
   `org-board-diff' :: uses `zdiff' (which itself uses the
   pre-installed `ediff') to recursively diff two archives of the same
   entry.
** Important options
   `org-board-wget-program' :: the path to the wget program.
   `org-board-wget-switches' :: the command line options to
   send by default to `wget'.
   `org-board-agent-header-alist' :: an alist mapping agent names to
   their respective header/user-agent arguments.  Set a WGET_OPTIONS
   property to the car of one of these lists (say, "MacOS10.8") and
   `wget' will replace it with its corresponding value in the alist.
   This is useful for some sites that do not serve pages to `wget'
   (like Google Cache).
   
